# Generated by Django 3.0.5 on 2020-06-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('thumbnail', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('access_level', models.CharField(choices=[('READ', 'READ'), ('WRITE', 'WRITE'), ('ADMIN', 'ADMIN'), ('COMMENT-ONLY', 'COMMENTONLY')], max_length=100)),
                ('due_date_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default='PENDING', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.Resource'),
        ),
    ]
