# Generated by Django 3.0.5 on 2020-07-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritems',
            name='access_level',
            field=models.CharField(choices=[('READ', 'READ'), ('WRITE', 'WRITE'), ('ADMIN', 'ADMIN'), ('COMMENT-ONLY', 'COMMENTONLY')], default='READ', max_length=100),
        ),
    ]
