# Generated by Django 3.0.5 on 2020-07-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0002_useritems_access_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user',
            new_name='user_id',
        ),
    ]
