# Generated by Django 3.0.5 on 2020-05-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0005_auto_20200529_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='users',
        ),
    ]
