# Generated by Django 3.0.5 on 2020-05-30 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0006_auto_20200530_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('READ', 'READ'), ('WRITE', 'WRITE'), ('ADMIN', 'ADMIN'), ('COMMENT-ONLY', 'COMMENTONLY')], max_length=100)),
                ('due_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT'), ('PENDING', 'PENDING')], max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
