# Generated by Django 3.0.5 on 2020-06-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0007_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], max_length=100, null=True),
        ),
    ]
