# Generated by Django 3.0.5 on 2020-06-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0008_auto_20200601_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='due_date',
            new_name='due_date_time',
        ),
    ]
