# Generated by Django 3.0.5 on 2020-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0009_auto_20200601_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default='PENDING', max_length=100),
        ),
    ]
